AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Esercizio06

  Sample SAM Template for Esercizio06

Globals:
  Function:
    Timeout: 3

Resources:
  UpdateItemDBFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
      - x86_64
      Events:
        SendProductAPI:
          Type: Api
          Properties:
            Path: /add
            Method: post
            RequestModel: !Ref SendProductModel
            RestApiId: !Ref ServerlessRestApi
      Environment:
        Variables:
          DYNAMOBD_TABLE: !Ref ProductsDB
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ProductsDB
  
  ProductsDB:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      AttributeDefinitions: 
        - 
          AttributeName: "PK"
          AttributeType: "N"
        - 
          AttributeName: "SK"
          AttributeType: "S"
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - 
          AttributeName: "PK"
          KeyType: "HASH"
        - 
          AttributeName: "SK"
          KeyType: "RANGE"
      TableName: ProductsDB

  SendProductModel:
    Type: 'AWS::ApiGateway::Model'
    Properties:
      Name: SendProductModel
      ContentType: application/json
      Schema:
        title: SendProductModel
        $schema: 'http://json-schema.org/draft-04/schema#'
        type: object
        properties:
          PK:
            type: number
          SK:
            type: string
        required:
          - PK
          - SK
      RestApiId: !Ref ServerlessRestApi

# Esempio API:
# {
#     "PK": 1,
#     "SK": "ProductDetails",
#     "marca": "Adidas",
#     "taglia": "XL",
#     "prezzo":4.5
# }